### ISSUE TITLE
[Bug] Can not install on vue above 3.2

### ISSUE THREAD

**Issue by VoOneCode** [VueFilesPreview/vue-files-preview#19]
## What happens?
unable to intall this package in project with vue higher than 3.2(vue@"3.4.21" in my case)

## How To Reproduce
npm i vue-files-preview 

**Expected behavior** 
Succesfully installed on vue@"3.4.21"

## Context

-   **vue-files-preview Version**: 1.0.31
-   **vue Version**: 3.4.21
-   **Platform**: win10x64

**Comment by SmallTeddy** [comment]
you can check this repo first https://github.com/VueFilesPreview/vue-files-preview-demo
