### ISSUE TITLE
[Bug] 文本文件不滚动,只显示第一屏内容

### ISSUE THREAD

**Issue by allran** [VueFilesPreview/vue-files-preview#80]
## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

-   **vue-files-preview Version**:
-   **Node Version**:
-   **Platform**:

**Comment by SmallTeddy** [comment]
我去测试一下 感谢反馈

**Comment by SmallTeddy** [comment]
已经增加 overflow 默认 auto 进行修复 更新至 v1.0.36 版本即可
