### ISSUE TITLE
[Bug] 当url不是以文件名结尾，而带的类似于file_path参数时，打开不了

### ISSUE THREAD

**Issue by allran** [VueFilesPreview/vue-files-preview#82]
示例：
http://127.0.0.1:8006/data/file?file_path=xxxxx/xxx.pdf

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

-   **vue-files-preview Version**:
-   **Node Version**:
-   **Platform**:

**Comment by SmallTeddy** [comment]
好的 我去实验一下

**Comment by SmallTeddy** [comment]
目前我在 `1.0.37`版本解决了 PdfPreview 使用 url 预览的问题 
我使用` <PdfPreview :src="https://www.pwithe.com/Public/Upload/download/20170211/589ebf8e5bb13.pdf" />`
测试是没有问题的
