### ISSUE TITLE
[Bug] 大图片时整个浏览器只显示左上部分,并不能滚动

### ISSUE THREAD

**Issue by allran** [VueFilesPreview/vue-files-preview#83]
## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

-   **vue-files-preview Version**:
-   **Node Version**:
-   **Platform**:

**Comment by SmallTeddy** [comment]
已经增加 overflow 默认 auto 进行修复 更新至 v1.0.36 版本即可
