### ISSUE TITLE
[Bug] 新版本报警告,文件还是不能滚动

### ISSUE THREAD

**Issue by allran** [VueFilesPreview/vue-files-preview#84]
使用版本："vue-files-preview": "^1.0.35"
我本地使用https://github.com/VueFilesPreview/vue-files-preview-demo/blob/main/src/App.vue代码，上传log文件后，还是不能滚动。报如下警告：
（索引）:5 [Vue warn]: Property "overflow" was accessed during render but is not defined on instance. 

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

-   **vue-files-preview Version**:
-   **Node Version**:
-   **Platform**:

**Comment by SmallTeddy** [comment]
已经增加 overflow 默认 auto 进行修复

**Comment by SmallTeddy** [comment]
请更新至 v1.0.36 版本
